### ISSUE TITLE
pre and post scripts should be indicated visually in diagram

### ISSUE THREAD

**Issue by burnettk** [sartography/bpmn-js-spiffworkflow#107]
Why should you have to click on the properties panel to see if there is a pre-script or post-script defined?
Couldn't we have a little icon in the bottom left of the activity for a pre-script and bottom right for a post-script?
This is along the same lines as sartography/bpmn-js-spiffworkflow#109, where little visual cues can go a long way.

Suggested by Volker.

See PR [#1990](https://github.com/sartography/spiff-arena/pull/1990) for the ever-present indicators on the element itself and PR https://github.com/sartography/bpmn-js-spiffworkflow/pull/112 for the improved UX to navigate to each script via the context pad.

**Comment by theaubmov** [comment]
@burnettk, In the feature/pre-and-post-scripts branch, I added some calls to actions for script, preScript and postScript at the level of the context pad. The visual call to action will always be displayed for ScriptTask since it's an important action. However, for pre-script and post-script, the call to actions will only appear if the user has already set them.

**Comment by burnettk** [comment]
i like it. i wonder if we can also always show the indicators on the task itself. we actually spent a bit of time on this today. they don't do anything, but are just an overlay. it seems like they might work together with what you have done here. will push up the stuff we were working on (in frontend, actually) tomorrow.

**Comment by burnettk** [comment]
we managed to add the icons to spiff-arena main. i think it sort of works. :D

**Comment by madhurrya** [comment]
@burnettk so we show the pre script post script icons only on the bpmn model and not in the instance diagram. Is that correct?




![Image](https://github.com/user-attachments/assets/a7155fb7-0659-4ae3-9e5f-de6b7faaecaf)





![Image](https://github.com/user-attachments/assets/fe812454-183a-4a76-b026-9e7e5c93dfd0)

**Comment by burnettk** [comment]
Yeah, they seemed less useful on the instance diagram and more likely to be perceived as unnecessary clutter.

**Comment by madhurrya** [comment]
As explained in the description, script icon is added to indicate pre scripts and post scripts. And icons to open the pre script editor and post script editor.
![image](https://github.com/user-attachments/assets/b6e6cf0e-d8bf-4891-9b5b-786e1d996726)
