### ISSUE TITLE
Navigating to Call Activities

### ISSUE THREAD

**Issue by calexh-sar** [sartography/bpmn-js-spiffworkflow#111]
From Slack post:
We can think of a couple possible ways the UI might be improved here:

- Call activities could be expanded into (or replace) the existing graph instead of opening a new tab
- And/or, perhaps, would it be possible to have a link in the Process Instances listing that could directly open the call activity that contains the current task?

**Comment by madhurrya** [comment]
@burnettk @jasquat If we go to a sub process then there's a breadcrumb to go back to the previous diagram. But when we go to a call activity we don't have a way to go back.


![Image](https://github.com/user-attachments/assets/aba45dad-2997-4f0b-8812-d473be443766)

**Comment by madhurrya** [comment]
When I click on the blue arrow, it doesn't open the call activity at once. It seems to reload the current diagram couple of times before opening the called activity. Please check this video. I think we should fix that.
https://drive.google.com/file/d/1FiBBXf6zsiuJ1hqVM4b9lXn7ZO9hy2Z3/view?usp=sharing

Was there any client requirement to open the called activity in the same diagram? What is the reason for not opening it in a new tab like we do for the BPMN diagram call activity?

**Comment by madhurrya** [comment]
Is this part also implemented '_And/or, perhaps, would it be possible to have a link in the Process Instances listing that could directly open the call activity that contains the current task?_'

**Comment by madhurrya** [comment]
For Multi instance/Loop call activities the arrow is not coming.

e.g. https://mysql.spiffcrm.com/i/45
![image](https://github.com/user-attachments/assets/3b8108da-0e56-4bc6-a922-fe25490c8145)

e.g. https://mysql.spiffcrm.com/i/47
![image](https://github.com/user-attachments/assets/5e2a5ed0-53b2-4547-8f67-792bd9de4dc9)

**Comment by jasquat** [comment]
@madhurrya this came from myome requests.

We did not implement the second bullet point. I think we we kinda can, but if there are multiple tasks ready in difference call activities, we wouldn't know which one to go to so this may not be possible with the current pi tables.

The way it loads is fact of life for now. It's the way react handles the state updates. There are probably some things we can do to improve it but it would take too much time for this ticket.

For the MI bug, I'm guessing it's coming in as a MI task and not a call activity. We'll probably have to put the link back in the Modal for situations like this. There'd be no way to know which call activity to use.

**Comment by jasquat** [comment]
Updates are on mysql.spiffcrm.com

**Comment by madhurrya** [comment]
Now the forward transition is much better with the loading icon. But when going back that issue is still there. But I guess you are not planning to fix it as we are currently using the page back button?

**Comment by jasquat** [comment]
Yeah, we are not planning on fixing that unless we stumble upon an easy fix.

**Comment by madhurrya** [comment]
Basic functionality is working as discussed above.

Suggestions for improvement later.
1. It might be nice to have an option to go back (similar to sub processes) instead of using the browser back button.
2. It will be nice to fix the transition issue when going back
