### ISSUE TITLE
pre and post script icons don't disappear when clearing script

### ISSUE THREAD

**Issue by burnettk** [sartography/bpmn-js-spiffworkflow#114]
If I delete the whole pre or post script, the script icon doesn’t disappear because the script tags in the xml are not deleted. it looks like:

`<spiffworkflow:postScript />`

If I delete the xml tag for the postScript then, for sure, the script icon disappears as well.

so we should delete the entire postScript xml node when the contents of the post script are empty.

See these files:
app/spiffworkflow/extensions/propertiesPanel/SpiffScriptGroup.js
app/spiffworkflow/extensions/propertiesPanel/ExtensionsPropertiesProvider.jsx

and test files inside of test/spec

**Comment by madhurrya** [comment]
This issue seems to be fixed now.
