### ISSUE TITLE
Data Object Reference Name - automatically changed

### ISSUE THREAD

**Issue by calexh-sar** [sartography/bpmn-js-spiffworkflow#54]
Data Object Reference Name must not be automatically changed if different Data Object is chosen.

# Overview
After reviewing the issues page with this discussion, I've listed below some errors/bugs I've found as well as an approach I suggest for good user experience and technical robustness.

![Image](https://github.com/sartography/bpmn-js-spiffworkflow/assets/54854669/127261f1-e5a6-488e-8a34-e16e3a8de9b2)

# Bugs Found

![Image](https://github.com/sartography/bpmn-js-spiffworkflow/assets/54854669/0515e5f3-a5d4-4ba3-b0fa-03bbbe7fbb2b)

![Image](https://github.com/sartography/bpmn-js-spiffworkflow/assets/54854669/a752885c-5e86-4d85-ace5-86ad949f4f43)

These errors can have an impact on the engine's processing level.

---

# Plan of implementation

- [ ]  Decoupling Data Reference Name from Data Object ID : prevent automatic updates that can confuse end-users.
    - On Change Data Object ID
    - On Change Data Object Reference (Dropdown)
- [ ]  Fixing bugs mentioned above and any new ones to avoid redundancy in the level of XML (engine impacts).
- [ ]  (Optional) We can enhance the user interface by adding color attributes or icons or legends so the user can see all the data reference objects that linked to the same data object without going through the properties panel.
- [ ]  Implement Test Cases

---

# Estimation

The estimation for this task isn't exactly straightforward because there's always a chance of encountering some unexpected errors along the way. However, if we set aside the OPTIONAL UI color feature, my initial estimate would be around 8 to 10 hours to complete the work.

**Comment by sashayar13** [comment]
@calexh-sar from my side, this ticket is leaning towards Medium-Low criticality, and if there are other critical tickets in the sprint, they should be picked up first @harmeet-status

**Comment by calexh-sar** [comment]
I understand the lower criticality of this ticket and I probably didn't make myself clear on @theaubmov availability.  We hired him as a contractor to exclusively work on BPMN.IO tickets since our developers were either not as efficient working in that code base periodically or had more critical work to do.  So having him to this work now would not affect the work getting done in a sprint.

**Comment by harmeet-status** [comment]
Should we need reference to the old Notion ticket, it is here: https://www.notion.so/Data-Object-Reference-Name-automatically-changed-06cd18c34ab94d779297f6120c1a99b5
