### ISSUE TITLE
Multi-Instance Output Element Removed when Reopened

### ISSUE THREAD

**Issue by danfunk** [sartography/bpmn-js-spiffworkflow#72]
If you open and then save [this example of a Multi-Instance task](https://spiffdemo.org/editor/process-models/examples:2-in-depth:2-5-loops:multi-instance/files/multi-instance.bpmn), it will remove the Output Element in the Multi-Instance section of the properties panel.  You must re-add ‘c’ to this every time the process is opened and saved or it will start to fail.  It is clear that adding it and saving it works, but for some reason, it gets removed on re-opening it.

**Comment by theaubmov** [comment]
I tried to reproduce the bug multiple times, but the input and output elements are not being deleted on opening the process and saving. One observation I made is that the loop cardinality is removed on changing the input collection, and vice versa, which I think is not a bug as we can't allow both.
