### ISSUE TITLE
Receive Message - Correlations from task data

### ISSUE THREAD

**Issue by danfunk** [sartography/bpmn-js-spiffworkflow#76]
It should be possible to set the correlation properties on a process instance from a Message Reieve Event/Task.

Currently we specify the correlation properties only when sending a message out of a process.  From that point forward the process is tied to those correlation properties.  This means you must either have sent a message to fix the correlation properties, or be willing to receive any a message with any correlation properties (Which you wound then adopt).

In the future, the BPMN.io Editor should allow you to optionally specify the correlation property values you wish to listen for.   - 

IMPORTANT:
This ticket is for the BPMN.io work to make it possible to set these values in an intuitive way.  Once the UI work is complete, create a ticket for the SpiffWorkflow Library that describes the new extension properties that will collect this information in the BPMN XML/

**Comment by madhurrya** [comment]
We can set correlation properties in the Receive tasks.
![image](https://github.com/sartography/bpmn-js-spiffworkflow/assets/110527567/a850bddf-af58-472f-a7de-fb9f56f5883d)

**Comment by theaubmov** [comment]
Yes, also in the receiving part, correlation properties should be included with the message in the XML.

Currently, we do not support the capability where user can select specific correlation properties in the receive task. All correlation properties of a message are used either for sending or receiving.

The new concept of Matching Condition replaces the flexibility of choosing specific correlation properties.

**Comment by burnettk** [comment]
do we close this given that we have implemented matching conditions?
